config/routes.rb
Rails.application.routes.draw do
  resources :payments

  # Commented to allow defaulting routing to splash index
  # devise_scope :user do
  #   # root 'devise/sessions#new'  
  # end

  root 'splash#index' 
  devise_for :users 

  get '/splash', to: 'splash#index', as: 'splash'

  resources :users, only: [:index, :show]
      resources :categories do
        resources :payments
    end
    

  # Defines the api routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
       resources :users, only: [:index, :show]
      resources :categories do
        resources :payments
    end
    end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_and_belongs_to_many :categories

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :user_id, presence: true
  validates :categories, presence: true, length: { minimum: 1 }
end

app/controllers/api/v1/payments_controller.rb
class Api::V1::PaymentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments/1 or /payments/1.json
  def index
    @category = Category.find(params[:category_id])
    @payments = @category.payments.order(created_at: :desc)

    respond_to do |format|
      format.json { render json: [@payments, @category], status: 200 }
    end
  end

  def show
    @category = Category.find(params[:category_id])
    @payment = Payment.find_by(id: params[:id])

    respond_to do |format|
      format.json { render json: [@payment, @category], status: 200 }
    end
  end

  # GET /payments/new
  def new
    @payment = current_user.payments.new
    @category = Category.find(params[:category_id])
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = current_user.payments.new(payment_params.merge(user_id: current_user.id).except(:categories))
    params[:categories].each do |key|
      @payment.categories << Category.find_by(id: key)
    end
    puts params[:categories]
    if @payment.save
      respond_to do |format|
        format.json { render json: @payment, status: :created }
      end
    else
      respond_to do |format|
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, :user_id, categories: [])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_payment, only: %i[show edit update destroy]

  def index
    @category = Category.find(params[:category_id])
    @payments = @category.payments.order(created_at: :desc)

    respond_to do |format|
      format.html
      format.json { render json: @payments, status: 200 }
    end
  end

  def create
    @payment = current_user.payments.new(payment_params.merge(user_id: current_user.id).except(:categories))
    params[:categories].each do |key|
      @payment.categories << Category.find_by(id: key)
    end
    puts params[:categories]
    if @payment.save

      redirect_to category_payments_path(params[:category_id]), notice: 'Payment successful created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @payment = current_user.payments.new
    @category = Category.find(params[:category_id])
  end

  def show
    @payment = Payment.find_by(id: params[:id])
  end

  def edit; end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, :user_id, categories: [])
  end
end

app/helpers/api/v1/payments_helper.rb
module Api::V1::PaymentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<% stylesheet_link_tag "form-category-list" %>
<body >
  
        <nav class="payment_nav"> 
        <ul>
               <a class="image" href="">
                <%=image_tag 'back.svg'%></a> 
                <a href="">NEW PAYMENTS</a> 
                <a href="">Next</a> 
                </ul>
        </nav>
        <main class="payment-main">

        <section class="sect-one-payment">
  
  <%= form_with(model: [@category, @payment], data:{turbo: false}) do |form| %>
    <% if payment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

        <ul>
          <% payment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="register_fieldset"> 
      <%= form.text_field :name, placeholder:"Name"  %>
    </div>

    <div class="register_fieldset"> 
      <%= form.number_field :amount, placeholder:"Amount" %>
    </div>

     <div class="category-list"> 
      <% current_user.categories.each do |categor| %>
        <li class="list_flex">
        <%= check_box_tag "categories[]", categor.id %>
        <%= form.label categor.name %>
        </li>
      <% end %>
    </div>  

    <div class="actions register_fieldset">
      <%= form.submit class:"login_input login_footer_fieldset" %>
    </div>
    
  <% end %> 
  </section>
  </main>
</body> 

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= payment.categories.size %>
  </p>

  <p>
    <strong>User:</strong>
    <%= payment.user_id %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<%= stylesheet_link_tag "transaction" %>
<body>
    <nav class="transaction-nav">
        <ul>
            <a class="image" href=""> <%=image_tag 'hamburger.png'%></a>
            <a href="">TRANSACTIONS</a> 
            <%= button_to ('Log Out'), destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } }, class:"sign_out_btn register_font2 td_none" %>
        </ul>
        <ul>
        <li><a href="" >Recent</a></li>
        <li><a href="" >Recent</a></li>
        <li><a href="" >Ancient</a></li>
    </ul>
    </nav>
    
 <main class="trans-main">
          <section class="sect-one-transaction">
            <% @payments.each do |payment| %>      
                <div class="sect-one-trans-cont">
                    <div class="sect-one-trans-cont-item-one">
                        <figure>
                            <% payment.categories.each do |key| %> 
                                <%=image_tag key.icon%>
                            <%end%>
                        </figure>
                         <div class="home_section2_article_box1_details">
                            <p class="home_font2"><%= link_to payment.name, payment, class:"td_none home_font2" %></p>
                            <p class="home_font2"><%=payment.created_at.strftime('%d %B %Y')%></p>
                        </div>
                    </div>
                    <div>
                        <p class="home_font3">$<%= payment.amount %></p>
                    </div>
                </div> 
            <% end %>
        </section>
    
            <section class="sect-two-category-show">
            <%= link_to "New Transaction", new_category_path %>  
        </section>
    
        </main>

</body>


   

app/views/payments/new.html.erb
<%= render "form", payment: @payment %>

<br>

<div>
  <p class="register_font4">
  <%= link_to 'Back to Category', category_path(@category), class:'td_none login_font3a', data:{turbo: false} %></p> 
</div>

app/views/payments/show.html.erb
<%= stylesheet_link_tag "detail" %>
<body>
    
        <nav class="detail-nav"> 
        <ul>
                <a class="image" href="../categories/1/payments">
                <%=image_tag 'back.svg'%></a>
                <a class="td_none details_font1" href="">DETAILS</a> 
                <%= button_to ('Log Out'), destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } }, class:"sign_out_btn register_font2 td_none" %>
        </ul>
                </nav>
   

    <main class="details_main"> 

       <section class="sect-one-detail">
                    <div class="sect-one-detail-cont">
                            <div class="sect-one-detail-cont-item">
                                    <% @payment.categories.each do |key| %> 
                                    <figure>
                                        <%=image_tag key.icon%>
                                 </figure> 
                                    <%end%>
                                    <p ><%= @payment.name %></p> 
                            </div>
                                        

                                <div class="sect-one-detail-desc">
                                 <p >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate cupiditate laborum molestias quo omnis laudantium hic quod quaerat labore? Cum doloribus minus illum ad! Nisi quod fuga omnis consequuntur deleniti.</p> 
                             </div> 
                             <hr>
                            <div class="sect-one-detail-date">
                                 <p >Transaction N000<%= @payment.id %>.</p>
                                    <p >
                                    <%=@payment.created_at.strftime('%d %B %Y')%>
                                 </p>
                            </div>
                            <hr>
                          <div class="sect-one-detail-amount"> 
                                <p >TOTAL PAYMENT </p>              
                    
                                 <p > $<%= @payment.amount %></p>  
                          </div>

        </div> 
       </section>
        
    </main> 
    <section class="sect-two-category-show">
        <%= link_to 'Back to users', users_path(@category), class:'td_none login_font3a' %>
        </section>
</body>