config/routes.rb
Rails.application.routes.draw do
  resources :payments

  # Commented to allow defaulting routing to splash index
  # devise_scope :user do
  #   # root 'devise/sessions#new'  
  # end

  root 'splash#index' 
  devise_for :users 

  get '/splash', to: 'splash#index', as: 'splash'

  resources :users, only: [:index, :show]
      resources :categories do
        resources :payments
    end
    

  # Defines the api routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
       resources :users, only: [:index, :show]
      resources :categories do
        resources :payments
    end
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_and_belongs_to_many :payments
  # has_many :payments, through :tablename

  def total_category_amount
    payments.where(user_id:).sum(:amount)
  end

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :user_id, presence: true
  validates :icon, presence: true
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.includes(:user).order(created_at: :desc).filter do |catego|
      catego.user_id == current_user.id
    end
    respond_to do |format|
      format.json { render json: @categories, status: 200 }
    end
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find_by(id: params[:id])
    respond_to do |format|
      format.json { render json: @category, status: 200 }
    end
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
    respond_to do |format|
      format.json { render json: @category, status: 200 }
    end
  end

  # GET /categories/1/edit
  def edit; end

  def create
    if params[:category][:icon].present?
      uploaded_file = params[:category][:icon].tempfile
      cloudinary_response = Cloudinary::Uploader.upload(uploaded_file.path, folder: 'budgeat')
      @category = current_user.categories.new(category_params.merge(user_id: current_user.id,
                                                                    icon: cloudinary_response['secure_url']))
    end

    if @category.save
      respond_to do |format|
        format.json { render json: @category, status: :created }
      end
    else
      respond_to do |format|
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    # params.require(:category).permit(:name, :icon, :total, :user_id)
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.includes(:user).order(created_at: :desc).filter do |catego|
      catego.user_id == current_user.id
    end
    respond_to do |format|
      format.html
      format.json { render json: @categories, status: 200 }
    end
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit; end

  def create
    if params[:category][:icon].present?
      uploaded_file = params[:category][:icon].tempfile
      cloudinary_response = Cloudinary::Uploader.upload(uploaded_file.path, folder: 'budgeat')
      @category = current_user.categories.new(category_params.merge(user_id: current_user.id,
                                                                    icon: cloudinary_response['secure_url']))
    end

    if @category.save
      redirect_to categories_url, notice: 'Categories created successfully'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    # params.require(:category).permit(:name, :icon, :total, :user_id)
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/helpers/api/v1/categories_helper.rb
module Api::V1::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
    <%=image_tag category.icon %>
  </p>

  <p>
    <strong>User:</strong>
    <%= category.user_id %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= stylesheet_link_tag "add-category" %>
<body class="body">
     
        <nav class="new-add-category-nav"> 
        <ul>
        <a class="image" href="../categories"><%=image_tag 'back.svg'%></a> 
                <a class="td_none register_font1" href="../categories">CATEGORY</a>
                <a class="td_none register_font2" href="">Next</a> 
                </ul>
        </nav>
   
        <main class="add-category-main">
        <section class="sect-one-add-category">
  <%= form_with(model: category, multipart: true, data:{turbo: false}) do |form| %>
    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="register_fieldset"> 
      <%= form.text_field :name, placeholder:"Name" %>
    </div>

    <div class="register_fieldset icon_box">
      <%= form.label :icon, style: "display: block" %>
      <%= form.file_field :icon, class:"inputfile" %>
    </div>

    <div class="actions register_fieldset">
      <%= form.submit class:"login_input login_footer_fieldset" %>
    </div>
  <% end %>
</section>
</main>
</body>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= stylesheet_link_tag "category" %>
<body>
    <nav class="nav_category" >
    <ul>
            <a class="image" href=""> <%=image_tag 'hamburger.png'%></a>
            <a class="td_none home_font1" href="">CATEGORIES</a> 
            <%= button_to ('Sign Out'), destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } }, class:"sign_out_btn" %>
    </ul>
            </nav>
   

     <main class="category_main">

        <section class="sect-one-category">
      <% @categories.each do |category| %> 


            <div class="sect-one-conatainer">
                <div class="sect-one-container-items">
                    
                    <%=image_tag category.icon%> 
                    
                    <div class="sect-one-cont-items-item-two">
                        <p><%= link_to category.name, category, class:"category-name", data:{turbo: false} %></p>
                        <p><%=category.created_at.strftime('%d %B %Y')%></p>
                    </div>
                </div>
                <div class="sect-one-container-item-three">
                    <%= link_to category.total_category_amount, category, class:"total-amount", data:{turbo: false} %>
                </div>
            </div>

      <% end %> 

        </section>

        <section class="sect-two-category-show">
            <%= link_to "New category", new_category_path %>  
        </section>

    </main>

</body>

app/views/categories/new.html.erb
<p style="color: green"><%= notice %></p>
<%= render "form", category: @category %>

<br>

<section class="sect-two-category-show">
 
  <%= link_to 'Back to categories', categories_path, class:'td_none login_font3a' %> 
</section>

app/views/categories/show.html.erb
<% stylesheet_link_tag "category_show" %>
<body class="body">
    
<nav class="nav_category-show" >
<ul>
        <a class="image" href=""> <%=image_tag 'hamburger.png'%></a>
        <a href="">CATEGORIES</a> 
        <%= button_to ('Sign Out'), destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } }, class:"sign_out_btn" %>
</ul>
        </nav>
    

    <main> 

       <section class="sect-one">

        <div class="sect-one-cat-show-container">
            <div class="sect-one-container-item-one">
                <%=image_tag @category.icon%>
                <p><%= @category.name %></p> 
            </div> 

            <div class="category-details">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate cupiditate laborum molestias quo omnis laudantium hic quod quaerat labore? Cum doloribus minus illum ad! Nisi quod fuga omnis consequuntur deleniti.</p> 
            </div> 

            <div class="transaction-detals">
                <p class="details_font3 details_font4">Transaction N000<%= @category.id %>.</p>
                <p class="details_font5">
                <%=@category.created_at.strftime('%d %B %Y')%>
                </p>
            </div>

            <div > 
                <p >TOTAL PAYMENT </p>              
                    
                <p > $<%= @category.total_category_amount %></p>  
            </div>  
 
        </div>
        
       </section>

         <section class="sect-two-category-show">
            <%= link_to "New Transaction", new_category_payment_path(@category), data:{turbo: false} %>  
        </section>
        
    </main> 

</body>